// Generate lib/generated/books.ts from deployments/<chainId>.json: only the addresses the web app uses,
// so the 1 MB deploy books stay out of the browser bundle. Run after every redeploy: `pnpm gen:books`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../../deployments");
const out = resolve(here, "../lib/generated/books.ts");

const pick = (chainId) => {
  const b = JSON.parse(readFileSync(resolve(root, `${chainId}.json`), "utf8"));
  const stack = b.stack;
  const s = b[stack];
  const markets = Object.fromEntries(
    Object.entries(s.markets).map(([sym, marketId]) => {
      const token = b.tokens[`t${sym}`] ?? null;
      return [sym, { marketId, assetId: b.assetIds[sym], token }];
    }),
  );
  return {
    chainId: b.chainId,
    stack,
    release: b.release ?? null,
    market: s.market,
    vault: s.vault,
    pool: s.pool,
    auctionHouse: s.auctionHouse ?? null,
    solverAuction: s.solverAuction ?? null,
    reserve: s.reserve ?? null,
    faucet: b.shared.faucet ?? null,
    loanToken: b.tokens.loan,
    markets,
  };
};

const books = [pick(46630), pick(421614)];
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/gen-books.mjs from deployments/<chainId>.json. Do not edit.\n` +
    `export const BOOKS = ${JSON.stringify(books, null, 2)} as const;\n`,
);
console.log(`gen-books: ${books.map((b) => `${b.chainId} (${Object.keys(b.markets).length} markets)`).join(", ")}`);
