#!/usr/bin/env bash
# make services-config CHAIN=46630|421614: A's address book → the per-chain env of the local testnet stack.
#
#   BOOK          the address book (default deployments/<CHAIN>.json; DRYRUN=1: deployments/31337.<stack>.dryrun.json)
#   DRYRUN=1      the book is a dry-run book (chain 31337 of the right stack); its copy gets chainId=<CHAIN>, because the
#                 dry-run anvil is switched to <CHAIN> (anvil_setChainId) before the stack starts
#   KEYS_DIR      the host keystore root (default $HOME/.credence/keys): <KEYS_DIR>/<CHAIN>/<role>.json + .password, 0600
#   GEN_DIR       where the env is written (default infra/prod/generated)
#
# Writes <GEN_DIR>/<CHAIN>/book.json (the book the services read, mounted at /run/config/book.json), chain.env (the
# services' env: addresses, start block, ABI tag, schemas, keystore dir, wallets to watch) and roles.txt (role →
# address, public). Refuses a book from another chain or stack, an unfinalized book, and a missing or group-readable
# keystore. Prints role names and addresses only, never a key, a password or an RPC URL.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
CHAIN="${CHAIN:?CHAIN=46630|421614}"
case "$CHAIN" in
  46630) STACK=equity; PUBLIC_RPC=https://rpc.testnet.chain.robinhood.com ;;
  421614) STACK=nav; PUBLIC_RPC=https://sepolia-rollup.arbitrum.io/rpc ;;
  *) echo "services-config: CHAIN must be 46630 or 421614" >&2; exit 2 ;;
esac
DRYRUN="${DRYRUN:-0}"
if [ "$DRYRUN" = 1 ]; then BOOK="${BOOK:-$ROOT/deployments/31337.$STACK.dryrun.json}"; WANT_CID=31337
else BOOK="${BOOK:-$ROOT/deployments/$CHAIN.json}"; WANT_CID="$CHAIN"; fi
KEYS_DIR="${KEYS_DIR:-$HOME/.credence/keys}"
GEN_DIR="${GEN_DIR:-$ROOT/infra/prod/generated}"
OUT="$GEN_DIR/$CHAIN"
ABI_TAG="${ABI_TAG:-v5-testnet}"
die() { echo "services-config: $*" >&2; exit 1; }

[ -f "$BOOK" ] || die "no address book $BOOK (A's deploy writes it)"
b() { jq -r "$1 // empty" "$BOOK"; }
[ "$(b .chainId)" = "$WANT_CID" ] || die "$BOOK is chain $(b .chainId), not $WANT_CID: refusing a book from another chain"
[ "$(b .stack)" = "$STACK" ] || die "$BOOK is the $(b .stack) stack; chain $CHAIN runs the $STACK stack"
[ "$(b .finalized)" = true ] || die "$BOOK is not finalized (FinalizeTestnet has not run)"
if [ -d "$ROOT/deployments/abis/$ABI_TAG" ]; then :; else
  echo "services-config: warning: deployments/abis/$ABI_TAG is not frozen yet (A's ABI tag); the services use the bindings in the tree" >&2
fi

# The keystore roles the stack needs on this chain (agreed with A on the board, 2026-10-01 17:06)
if [ "$STACK" = equity ]; then
  ROLES="keeper relayer-a-node-1 relayer-a-node-2 relayer-a-node-3 relayer-b-node-1 relayer-b-node-2 relayer-b-node-3
         relayer-a-submitter relayer-b-submitter sigma-1 sigma-2 sigma-3"
  WATCH_ROLES="relayer-a-submitter relayer-b-submitter"
else
  ROLES="keeper sigma-1 sigma-2 sigma-3 nav-1 nav-2 nav-3 nav-submitter issuer solver-main"
  WATCH_ROLES="nav-submitter issuer solver-main"
fi
mode() { stat -c %a "$1"; }
mkdir -p "$OUT"; chmod 700 "$OUT"
: > "$OUT/roles.txt"
missing=0
for r in $ROLES; do
  ks="$KEYS_DIR/$CHAIN/$r.json"; pw="$KEYS_DIR/$CHAIN/$r.password"
  if [ ! -f "$ks" ] || [ ! -f "$pw" ]; then echo "  missing keystore role $r" >&2; missing=1; continue; fi
  for f in "$ks" "$pw"; do
    case "$(mode "$f")" in 600|400) ;; *) die "$f must be 0600 (it is $(mode "$f"))" ;; esac
  done
  addr="$(jq -r '.address // empty' "$ks")"
  [ -n "$addr" ] && addr="0x${addr#0x}" || addr="$(cast wallet address --keystore "$ks" --password-file "$pw")"
  echo "$r=$(cast to-check-sum-address "$addr")" >> "$OUT/roles.txt"
done
[ "$missing" = 0 ] || die "keystores missing under $KEYS_DIR/$CHAIN (A's make testnet-keys CHAIN=$CHAIN KEYSTORE_DIR=$KEYS_DIR)"
role_addr() { sed -n "s/^$1=//p" "$OUT/roles.txt"; }

# The book the services read: the dry run's copy is re-labelled with the chain the anvil now reports
jq --argjson c "$CHAIN" '.chainId = $c' "$BOOK" > "$OUT/book.json"
START_BLOCK="$(b .startBlock)"; START_BLOCK="${START_BLOCK:-0}"
watch=""
for r in $WATCH_ROLES; do watch="${watch:+$watch,}$r=$(role_addr "$r")"; done

{
  echo "# generated by make services-config CHAIN=$CHAIN from $(basename "$BOOK") at $(date -u +%FT%TZ); do not edit"
  echo "CHAIN_ID=$CHAIN"
  echo "STACK=$STACK"
  echo "ABI_TAG=$ABI_TAG"
  echo "RELEASE=$(b .release)"
  echo "START_BLOCK=$START_BLOCK"
  echo "DEPLOYMENTS_FILE=/run/config/book.json"
  echo "KEYSTORE_DIR=/run/keys"
  echo "RPC_CHAINS=$CHAIN"
  echo "PONDER_CHAIN_ID=$CHAIN"
  echo "DATABASE_SCHEMA=indexer_$CHAIN"
  echo "VIEWS_SCHEMA=ix_$CHAIN"
  echo "INDEXER_SCHEMA=ix_$CHAIN"
  echo "WATCH_WALLETS=$watch"
  echo "SIGMA_COMMITTEE_SIZE=3"
  # testnet: the keeper sends (the S3 dry-run defaults are off); J3 batch from A's measure (ADR-0114)
  echo "KEEPER_J3_LIVE=1"
  echo "KEEPER_J4_LIVE=1"
  echo "KEEPER_J3_BATCH=9"
  echo "CLOCK_ADDRESS=$(b .shared.clock)"
  if [ "$STACK" = equity ]; then
    # the relayer's six test tickers, plus the official Robinhood TSLA under its own id (ADR-0120)
    assets="$(jq -r '.assetIds | keys[] | select(. != "RHTSLA")' "$BOOK" | sed 's/$/:XNAS/' | paste -sd, -)"
    jq -e '.assetIds.RHTSLA' "$BOOK" >/dev/null && assets="$assets,RHTSLA:XNAS=TSLA"
    echo "ASSETS=$assets"
    echo "KEEPER_ASSETS=$(jq -r '.assetIds | keys[]' "$BOOK" | sed 's/$/:XNAS/' | paste -sd, -)"
    echo "FEED_A_ADDRESS=$(b .shared.feedA)"
    echo "FEED_B_ADDRESS=$(b .shared.feedB)"
    echo "VENDOR=redstone"
  else
    echo "ASSETS="
    echo "KEEPER_ASSETS=TBILL:USBANK"
    echo "FEED_NAV_ADDRESS=$(b .shared.feedNav)"
    echo "SOLVER_AUCTION=$(b .nav.solverAuction)"
    echo "NAV_COMMITTEE_SIZE=2"
  fi
} > "$OUT/chain.env"
# the keyless public endpoint is the last failover (the user's two keyed providers come first, entrypoint.sh)
if [ "$DRYRUN" = 1 ]; then echo "RPC_${CHAIN}_PUBLIC=${DRY_RPC_URL:?DRY_RPC_URL for the dry run}" >> "$OUT/chain.env"
else echo "RPC_${CHAIN}_PUBLIC=$PUBLIC_RPC" >> "$OUT/chain.env"; fi
if [ "$STACK" = equity ]; then   # one env per relayer committee (compose can't interpolate env_file values)
  for f in A B; do
    lf="$(echo "$f" | tr A-Z a-z)"
    printf 'FEED_ID=%s\nFEED_ADDRESS=%s\nRELAYER_NODE_URLS=http://relayer-%s-node-1:8080,http://relayer-%s-node-2:8080,http://relayer-%s-node-3:8080\n' \
      "$f" "$(b ".shared.feed$f")" "$lf" "$lf" "$lf" > "$OUT/feed-$lf.env"
    chmod 600 "$OUT/feed-$lf.env"
  done
else   # the NAV stack's solver bot: one profile, keystore role solver-main
  echo '{"solvers":[{"name":"main","bid":true,"premium_bps":0,"max_bps":10}]}' > "$OUT/solvers.json"
  chmod 644 "$OUT/solvers.json"
fi
chmod 600 "$OUT/chain.env" "$OUT/roles.txt"; chmod 644 "$OUT/book.json"

# The one API and the one notifier serve every configured chain (ADR-0014): their env from every chain dir present
chains=""; for d in "$GEN_DIR"/46630 "$GEN_DIR"/421614; do [ -f "$d/chain.env" ] && chains="$chains $(basename "$d")"; done
{
  echo "# generated by make services-config; the API's and the notifier's chains: $chains"
  echo "API_CHAINS=$(for c in $chains; do printf '%s:ix_%s,' "$c" "$c"; done | sed 's/,$//')"
  echo "NOTIFIER_CHAINS=$(echo $chains | tr ' ' ',')"
  echo "RPC_CHAINS=$(echo $chains)"
  for c in $chains; do
    echo "INDEXER_SCHEMA_$c=ix_$c"
    echo "DEPLOYMENTS_FILE_$c=/run/config/$c/book.json"
    echo "ASSETS_$c=$(sed -n 's/^KEEPER_ASSETS=//p' "$GEN_DIR/$c/chain.env")"
    sed -n "s/^RPC_${c}_PUBLIC=/RPC_${c}_PUBLIC=/p" "$GEN_DIR/$c/chain.env"
  done
} > "$GEN_DIR/stack.env"
chmod 600 "$GEN_DIR/stack.env"

echo "services-config: chain $CHAIN ($STACK) from $(basename "$BOOK"), start block $START_BLOCK, ABI $ABI_TAG → ${OUT#$ROOT/}"
sed 's/^/  /' "$OUT/roles.txt"
