//! Venue calendars as generated by `calibration/credence_cal/calendar.py` (§8.2.1). Off-chain services
//! use the same `Session[]` the `CalendarStore` holds, so their view of time matches the chain's.

use anyhow::{bail, Context, Result};
use serde::Deserialize;
use std::path::Path;

/// `ClosureType` (Types.sol).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize)]
#[repr(u8)]
pub enum ClosureType {
    None = 0,
    Overnight = 1,
    Weekend = 2,
    HolidayWeekend = 3,
    Halt = 4,
    CorpAction = 5,
}

impl TryFrom<u8> for ClosureType {
    type Error = anyhow::Error;
    fn try_from(v: u8) -> Result<Self> {
        Ok(match v {
            0 => Self::None,
            1 => Self::Overnight,
            2 => Self::Weekend,
            3 => Self::HolidayWeekend,
            4 => Self::Halt,
            5 => Self::CorpAction,
            _ => bail!("bad ClosureType {v}"),
        })
    }
}

/// One session, UTC unix seconds. Mirrors `struct Session` in Types.sol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Session {
    pub ext_open: u64,
    pub open: u64,
    pub close: u64,
    pub ext_close: u64,
    pub closure_type_after: ClosureType,
}

/// Where a timestamp falls relative to the venue's sessions. Pre-market starts 5 h 30 min before the
/// regular open (04:00 ET for XNYS); an earlier `extOpen` is the 24/5 overnight window.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize)]
pub enum Window {
    Closed,
    Overnight,
    Pre,
    Regular,
    Post,
}

impl Window {
    pub fn is_extended(self) -> bool {
        matches!(self, Self::Overnight | Self::Pre | Self::Post)
    }
}

pub const PRE_MARKET_LEAD: u64 = 5 * 3600 + 30 * 60;

/// A loaded venue calendar.
#[derive(Debug, Clone)]
pub struct Calendar {
    pub venue: String,
    pub sessions: Vec<Session>,
    pub content_hash: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Doc {
    format_version: u32,
    venue: String,
    content_hash: String,
    sessions: Vec<RawSession>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RawSession {
    ext_open: u64,
    open: u64,
    close: u64,
    ext_close: u64,
    closure_type_after: u8,
}

impl Calendar {
    pub fn load(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        let raw =
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        Self::from_json(&raw).with_context(|| format!("parsing {}", path.display()))
    }

    pub fn from_json(raw: &str) -> Result<Self> {
        let doc: Doc = serde_json::from_str(raw)?;
        if doc.format_version != 1 {
            bail!("unsupported calendar formatVersion {}", doc.format_version);
        }
        let sessions = doc
            .sessions
            .into_iter()
            .map(|s| {
                Ok(Session {
                    ext_open: s.ext_open,
                    open: s.open,
                    close: s.close,
                    ext_close: s.ext_close,
                    closure_type_after: ClosureType::try_from(s.closure_type_after)?,
                })
            })
            .collect::<Result<Vec<_>>>()?;
        let cal = Self {
            venue: doc.venue,
            sessions,
            content_hash: doc.content_hash,
        };
        cal.validate()?;
        Ok(cal)
    }

    /// Build from sessions directly (tests, time-warped replays).
    pub fn from_sessions(venue: &str, sessions: Vec<Session>) -> Result<Self> {
        let cal = Self {
            venue: venue.into(),
            sessions,
            content_hash: String::new(),
        };
        cal.validate()?;
        Ok(cal)
    }

    /// Merge calendars for the same venue (e.g. this year's and next year's load), dropping duplicates.
    pub fn merge(mut self, other: Calendar) -> Result<Self> {
        if self.venue != other.venue {
            bail!("cannot merge {} with {}", self.venue, other.venue);
        }
        self.sessions.extend(other.sessions);
        self.sessions.sort_by_key(|s| s.open);
        self.sessions.dedup_by_key(|s| s.open);
        self.validate()?;
        Ok(self)
    }

    fn validate(&self) -> Result<()> {
        for (i, s) in self.sessions.iter().enumerate() {
            if !(s.ext_open < s.open && s.open < s.close && s.close < s.ext_close) {
                bail!("session {i} not strictly increasing");
            }
            if i > 0 {
                let p = &self.sessions[i - 1];
                if s.open <= p.close || s.ext_open < p.ext_close {
                    bail!("session {i} overlaps session {}", i - 1);
                }
            }
        }
        Ok(())
    }

    /// Close of the last loaded session (`CalendarStore.coverageEnd`).
    pub fn coverage_end(&self) -> u64 {
        self.sessions.last().map(|s| s.close).unwrap_or(0)
    }

    /// Index of the session whose extended span `[extOpen, extClose)` contains `t`, if any.
    pub fn session_index_at(&self, t: u64) -> Option<usize> {
        let i = self.sessions.partition_point(|s| s.ext_close <= t);
        (i < self.sessions.len() && self.sessions[i].ext_open <= t).then_some(i)
    }

    pub fn session_at(&self, t: u64) -> Option<&Session> {
        self.session_index_at(t).map(|i| &self.sessions[i])
    }

    /// The first session whose regular open is at or after `t`.
    pub fn next_session(&self, t: u64) -> Option<&Session> {
        let i = self.sessions.partition_point(|s| s.open < t);
        self.sessions.get(i)
    }

    /// The most recent session whose regular open is at or before `t`.
    pub fn current_or_last_session(&self, t: u64) -> Option<&Session> {
        let i = self.sessions.partition_point(|s| s.open <= t);
        i.checked_sub(1).map(|i| &self.sessions[i])
    }

    pub fn window_at(&self, t: u64) -> Window {
        if t > self.coverage_end() {
            return Window::Closed;
        }
        match self.session_at(t) {
            None => Window::Closed,
            Some(s) if t >= s.open && t < s.close => Window::Regular,
            Some(s) if t >= s.close => Window::Post,
            Some(s) if t + PRE_MARKET_LEAD >= s.open => Window::Pre,
            Some(_) => Window::Overnight,
        }
    }

    /// Every distinct session boundary (extOpen, open, close, extClose) in `(from, to]`, ascending.
    pub fn boundaries_between(&self, from: u64, to: u64) -> Vec<u64> {
        let mut out: Vec<u64> = self
            .sessions
            .iter()
            .filter(|s| s.ext_close > from && s.ext_open <= to)
            .flat_map(|s| [s.ext_open, s.open, s.close, s.ext_close])
            .filter(|&b| b > from && b <= to)
            .collect();
        out.sort_unstable();
        out.dedup();
        out
    }

    /// `Report.sessionDate` for the session a print belongs to: floor(regularOpenUtc / 86400) (ADR-0101).
    pub fn session_date(s: &Session) -> u64 {
        s.open / 86_400
    }
}

/// The newest `<VENUE>-*.json` under `calibration/out/calendars/`, searching from the working directory
/// upwards (so services find the repo's calendars when started from any subdirectory).
pub fn find_latest(venue: &str) -> Result<std::path::PathBuf> {
    let mut dir = std::env::current_dir()?;
    loop {
        let d = dir.join("calibration/out/calendars");
        if d.is_dir() {
            let prefix = format!("{venue}-");
            let mut xs: Vec<std::path::PathBuf> = std::fs::read_dir(&d)?
                .filter_map(|e| e.ok().map(|e| e.path()))
                .filter(|p| {
                    p.file_name()
                        .and_then(|n| n.to_str())
                        .is_some_and(|n| n.starts_with(&prefix) && n.ends_with(".json"))
                })
                .collect();
            xs.sort();
            return xs.pop().ok_or_else(|| {
                anyhow::anyhow!(
                    "no {venue} calendar in {} (run `make calendar-gen`)",
                    d.display()
                )
            });
        }
        if !dir.pop() {
            bail!("calibration/out/calendars not found; set CALENDAR_FILES");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_calendar() -> Calendar {
        let p = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../calibration/out/calendars/XNYS-20261001-20271031.json"
        );
        Calendar::load(p).unwrap()
    }

    #[test]
    fn loads_the_generated_calendar() {
        let c = repo_calendar();
        assert_eq!(c.venue, "XNYS");
        assert!(c.sessions.len() > 250);
    }

    #[test]
    fn windows_through_a_weekday() {
        let c = repo_calendar();
        // Wed 2026-10-07 in EDT (UTC-4): 09:30 ET = 13:30Z
        let open = 1_791_331_200 + 13 * 3600 + 30 * 60; // 2026-10-07T13:30Z
        let s = c.session_at(open).unwrap();
        assert_eq!(s.open, open);
        assert_eq!(c.window_at(open), Window::Regular);
        assert_eq!(c.window_at(open - 1), Window::Pre);
        assert_eq!(c.window_at(open - PRE_MARKET_LEAD), Window::Pre);
        assert_eq!(c.window_at(open - PRE_MARKET_LEAD - 1), Window::Overnight);
        assert_eq!(c.window_at(s.close), Window::Post);
        assert_eq!(c.window_at(s.close - 1), Window::Regular);
        // Tue 20:00 ET → Wed session's extOpen: overnight
        assert_eq!(c.window_at(s.ext_open), Window::Overnight);
    }

    #[test]
    fn weekend_is_closed_and_boundaries_are_listed() {
        let c = repo_calendar();
        // Sat 2026-10-10 12:00Z
        let sat = 1_791_633_600;
        assert_eq!(c.window_at(sat), Window::Closed);
        let fri = c.current_or_last_session(sat).unwrap();
        assert_eq!(fri.closure_type_after, ClosureType::Weekend);
        let mon = c.next_session(sat).unwrap();
        let b = c.boundaries_between(fri.open - 1, mon.open);
        assert_eq!(
            b,
            vec![fri.open, fri.close, fri.ext_close, mon.ext_open, mon.open]
        );
        assert_eq!(Calendar::session_date(fri), fri.open / 86_400);
    }

    #[test]
    fn beyond_coverage_is_closed() {
        let c = repo_calendar();
        assert_eq!(c.window_at(c.coverage_end() + 1), Window::Closed);
    }
}
