#!/usr/bin/env python3
"""Compare two frozen ABI directories (deployments/abis/<old> → <new>) and write a changelog.

Every entry is keyed by its signature (type + name + input types). The check fails if an entry of `old` is
missing from `new` (a breaking change) unless the signature is listed in ALLOWED_BREAKS with a reason.

    python3 contracts/script/abi_diff.py deployments/abis/v0 deployments/abis/v1 [--write CHANGELOG.md]
"""
import json
import sys
from pathlib import Path

# Deliberate breaking changes between v0 and v1, with the rule that requires them.
ALLOWED_BREAKS = {
    "event ReportAccepted(bytes32,uint8,uint256,uint40,uint64)": "R-25: replaced by the 6-argument event with marketStatus",
}


def canon(t):
    if t["type"].startswith("tuple"):
        return "(" + ",".join(canon(c) for c in t["components"]) + ")" + t["type"][5:]
    return t["type"]


def sig(e):
    if e["type"] in ("constructor", "fallback", "receive"):
        return e["type"]
    return f'{e["type"]} {e["name"]}(' + ",".join(canon(i) for i in e.get("inputs", [])) + ")"


def load(d):
    out = {}
    for f in sorted(Path(d).glob("*.json")):
        out[f.stem] = {sig(e): e for e in json.loads(f.read_text())}
    return out


def main():
    old_dir, new_dir = sys.argv[1], sys.argv[2]
    write = sys.argv[sys.argv.index("--write") + 1] if "--write" in sys.argv else None
    old, new = load(old_dir), load(new_dir)
    breaks, lines = [], []
    lines.append(f"# ABI changes {Path(old_dir).name} → {Path(new_dir).name}\n")
    lines.append("Generated by `contracts/script/abi_diff.py`. Additive unless listed under *Breaking*.\n")
    # errors added to the shared catalogue show up in every ABI that inherits it; list them once
    common_added = set(new.get("ICredenceErrors", {})) - set(old.get("ICredenceErrors", {}))
    per_file = {}
    for name in sorted(set(old) | set(new)):
        o, n = old.get(name, {}), new.get(name, {})
        if name not in new:
            breaks.append(f"{name}: file removed")
            continue
        added = sorted(set(n) - set(o))
        removed = sorted(set(o) - set(n))
        changed = sorted(s for s in set(o) & set(n) if o[s].get("outputs") != n[s].get("outputs")
                         or o[s].get("stateMutability") != n[s].get("stateMutability"))
        for s in removed + changed:
            if s not in ALLOWED_BREAKS:
                breaks.append(f"{name}: {s}")
        per_file[name] = (name not in old, added, removed, changed)
    if common_added:
        lines.append("## Added to every ABI (the shared `ICredenceErrors` catalogue)\n")
        lines += [f"- `{s}`" for s in sorted(common_added)]
        lines.append("")
    lines.append("## Breaking\n")
    lines += [f"- `{s}`: {why}" for s, why in ALLOWED_BREAKS.items()] or ["- none"]
    lines.append("")
    lines.append("## Per file\n")
    for name, (is_new, added, removed, changed) in per_file.items():
        own = [s for s in added if s not in common_added]
        if not (is_new or own or removed or changed):
            continue
        lines.append(f"### {name}{' (new)' if is_new else ''}\n")
        if is_new:
            lines.append(f"- {len(added)} entries")
        lines += [f"- added `{s}`" for s in own if not is_new]
        lines += [f"- removed `{s}`" for s in removed]
        lines += [f"- changed outputs/mutability `{s}`" for s in changed]
        lines.append("")
    text = "\n".join(lines)
    if write:
        Path(write).write_text(text)
    if breaks:
        print("UNEXPECTED BREAKING CHANGES:\n  " + "\n  ".join(breaks), file=sys.stderr)
        sys.exit(1)
    print(f"ok: {len(per_file)} ABIs, additive except {len(ALLOWED_BREAKS)} allowed break(s)")


if __name__ == "__main__":
    main()
