// Generate `src/generated/abis.ts` from the frozen ABIs in deployments/abis/v0 (owned by BE-chain),
// so viem gets literal ABI types (`as const`). Run by build, typecheck and test.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const version = process.env.ABI_VERSION ?? "v0";
const src = resolve(here, "../../../deployments/abis", version);
const out = resolve(here, "../src/generated");
mkdirSync(out, { recursive: true });

const files = readdirSync(src).filter((f) => f.endsWith(".json")).sort();
let ts = `// GENERATED by scripts/gen-abis.mjs from deployments/abis/${version}. Do not edit.\n`;
ts += `export const ABI_VERSION = ${JSON.stringify(version)} as const;\n`;
const names = [];
for (const f of files) {
  const raw = JSON.parse(readFileSync(join(src, f), "utf8"));
  const abi = Array.isArray(raw) ? raw : raw.abi;
  const name = f.replace(/\.json$/, "") + "Abi";
  names.push(name);
  ts += `export const ${name} = ${JSON.stringify(abi)} as const;\n`;
}
ts += `export const abis = { ${names.join(", ")} } as const;\n`;
writeFileSync(join(out, "abis.ts"), ts);
console.log(`gen-abis: ${files.length} ABIs from ${src}`);
