#!/usr/bin/env bash
# Generate the Stylus build workspace for the Risk Engine under target/stylus-ws (git-ignored) and print its path.
#
# Why: cargo-stylus 0.10 needs a `Stylus.toml` at the cargo workspace root, and the repo root is shared with other
# roles. The generated workspace symlinks the two crates, copies the root [workspace.*] tables, and pins the
# on-chain build (ADR-0102):
#   - toolchain  : nightly-2025-08-01, wasm32-unknown-unknown + rust-src (cargo-stylus adds
#                  -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort on nightly;
#                  later nightlies renamed that to the `immediate-abort` panic strategy)
#   - build-std  : std + panic_abort with panic_immediate_abort → no panic formatting code on-chain
#   - profile    : release = opt-level "z", lto, codegen-units 1, strip
# With this build the engine is one Stylus code fragment (< 24 KB compressed), as ArbOS 40 requires.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
WS="$ROOT/target/stylus-ws"
NIGHTLY="${STYLUS_NIGHTLY:-nightly-2025-08-01}"
mkdir -p "$WS/crates" "$WS/stylus"
ln -sfn "$ROOT/crates/risk-core" "$WS/crates/risk-core"
ln -sfn "$ROOT/stylus/risk-engine" "$WS/stylus/risk-engine"
{
  echo '[workspace]'
  echo 'resolver = "2"'
  echo 'members = ["crates/risk-core", "stylus/risk-engine"]'
  echo
  # copy [workspace.package] and [workspace.dependencies] verbatim from the root manifest
  awk '/^\[workspace\.(package|dependencies)\]/{p=1; print; next} /^\[/{p=0} p' "$ROOT/Cargo.toml"
  cat <<'TOML'

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
opt-level = "z"
strip = true
debug = false
TOML
} > "$WS/Cargo.toml"
printf '# Stylus workspace marker (generated by stylus/risk-engine/scripts/stylus-ws.sh)\n[workspace]\n\n[workspace.networks]\ndevnode = { endpoint = "http://127.0.0.1:8547" }\n' > "$WS/Stylus.toml"
printf '[toolchain]\nchannel = "%s"\ncomponents = ["rust-src"]\ntargets = ["wasm32-unknown-unknown"]\n' "$NIGHTLY" > "$WS/rust-toolchain.toml"
rm -f "$WS/.cargo/config.toml"
[ -f "$ROOT/Cargo.lock" ] && [ ! -f "$WS/Cargo.lock" ] && cp "$ROOT/Cargo.lock" "$WS/Cargo.lock"
# prune the copied lock to this workspace (versions of shared deps are kept)
(cd "$WS" && cargo metadata --format-version 1 >/dev/null)
echo "$WS"
