"""Step 1: pull raw daily data and pin it with a committed manifest (§10.6 step 1, ADR-0201).

    python -m credence_cal.data pull  --vendor alpaca [--end 2026-09-25]
    python -m credence_cal.data verify --vendor alpaca

Raw Parquet goes to `calibration/data/raw/<vendor>/<SYMBOL>.parquet` (git-ignored). The manifest
`calibration/manifests/data-<vendor>.json` (committed) records source, licence grade, pull date, the
requested window, and per symbol the row count, first/last date and two checksums:
`contentSha256` over a canonical CSV of the rows (stable across pyarrow versions; this is what the
pipeline pins) and `fileSha256` over the Parquet bytes.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import pandas as pd

from .common import DATA, LISTED, MANIFESTS, load_env, sha256_hex, universe, write_json
from .vendors import VENDORS

LICENCE = {
    "alpaca": {"grade": "dev-unlicensed", "terms": "Alpaca Basic market data: personal, non-professional use "
               "only. Not licensed for internal business model use. Development runs only (ADR-0201)."},
    "tiingo": {"grade": "licensed-internal", "terms": "Tiingo Power, business licence: internal business use "
               "(no redistribution of prices). Derived z-sets are not prices (ADR-0201)."},
    "sample": {"grade": "synthetic", "terms": "Synthetic CI sample generated by credence_cal.sample; no vendor data."},
}
START = {"alpaca": "2016-01-01", "tiingo": "2000-01-01"}


def raw_dir(vendor: str) -> Path:
    return DATA / "raw" / vendor


def content_sha(df: pd.DataFrame) -> str:
    return sha256_hex(df.to_csv(index=False, lineterminator="\n").encode())


def load_raw(vendor: str, symbol: str) -> pd.DataFrame:
    if vendor == "sample":
        from .sample import sample_frame

        return sample_frame(symbol)
    return pd.read_parquet(raw_dir(vendor) / f"{symbol}.parquet")


def manifest_path(vendor: str) -> Path:
    return MANIFESTS / f"data-{vendor}.json"


def pull(vendor: str, end: str, symbols: list[str]) -> None:
    env = load_env()
    v = VENDORS[vendor](env)
    out = raw_dir(vendor)
    out.mkdir(parents=True, exist_ok=True)
    entries = {}
    for s in symbols:
        df = v.daily(s, START[vendor], end)
        df.to_parquet(out / f"{s}.parquet", index=False)
        entries[s] = {
            "rows": len(df),
            "first": df["date"].iloc[0] if len(df) else None,
            "last": df["date"].iloc[-1] if len(df) else None,
            "splits": int((df["split_ratio"] != 1.0).sum()),
            "dividends": int((df["dividend"] != 0.0).sum()),
            "contentSha256": content_sha(df),
            "fileSha256": sha256_hex((out / f"{s}.parquet").read_bytes()),
        }
        print(f"{s:6} {entries[s]['rows']:5} rows {entries[s]['first']} .. {entries[s]['last']}", flush=True)
    manifest = {
        "vendor": vendor,
        "licence": LICENCE[vendor],
        "pulledAt": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "window": {"start": START[vendor], "end": end},
        "listed": list(LISTED),
        "symbols": entries,
    }
    write_json(manifest_path(vendor), manifest)
    print(f"manifest -> {manifest_path(vendor)}")


def verify(vendor: str) -> dict:
    """Check every raw file against the committed manifest; return the manifest. Raises on mismatch."""
    import json

    m = json.loads(manifest_path(vendor).read_text())
    bad = []
    for s, e in m["symbols"].items():
        p = raw_dir(vendor) / f"{s}.parquet"
        if not p.exists():
            bad.append(f"{s}: missing {p}")
            continue
        got = content_sha(pd.read_parquet(p))
        if got != e["contentSha256"]:
            bad.append(f"{s}: content sha {got[:12]} != manifest {e['contentSha256'][:12]}")
    if bad:
        raise SystemExit("raw data does not match the pinned manifest:\n  " + "\n  ".join(bad))
    return m


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(prog="credence_cal.data")
    ap.add_argument("cmd", choices=["pull", "verify"])
    ap.add_argument("--vendor", default="alpaca", choices=list(VENDORS))
    ap.add_argument("--end", default=None, help="last date to pull (default: yesterday)")
    ap.add_argument("--symbols", default=None, help="comma-separated (default: listed + comparables)")
    a = ap.parse_args(argv)
    if a.cmd == "pull":
        end = a.end or (dt.date.today() - dt.timedelta(days=1)).isoformat()
        pull(a.vendor, end, a.symbols.split(",") if a.symbols else universe())
    else:
        m = verify(a.vendor)
        print(f"{len(m['symbols'])} symbols match manifest-{a.vendor} (pulled {m['pulledAt']})")


if __name__ == "__main__":
    sys.exit(main())
