"""Step 1: pull raw daily data and pin it with a committed manifest (§10.6 step 1, ADR-0201).

    python -m credence_cal.data pull  --vendor alpaca [--end 2026-09-25]
    python -m credence_cal.data verify --vendor alpaca
    python -m credence_cal.data crosscheck           (Alpaca vs Polygon official open/close, last 2 years)

Raw Parquet goes to `calibration/data/raw/<vendor>/<SYMBOL>.parquet` (git-ignored). The manifest
`calibration/manifests/data-<vendor>.json` (committed) records source, licence grade, pull date, the
requested window, and per symbol the row count, first/last date and two checksums:
`contentSha256` over a canonical CSV of the rows (stable across pyarrow versions; this is what the
pipeline pins) and `fileSha256` over the Parquet bytes.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import pandas as pd

from .common import DATA, LISTED, MANIFESTS, load_env, sha256_hex, universe, write_json
from .vendors import VENDORS

LICENCE = {
    "alpaca": {"grade": "free-2016", "terms": "Alpaca Basic (free) market data, SIP daily bars from 2016-01-04: "
               "personal, non-professional licence. Accepted by the user for the S2 testnet calibration; the PM "
               "re-opens licensing before mainnet (ADR-0204)."},
    "tiingo": {"grade": "licensed-internal", "terms": "Tiingo Power, business licence: internal business use "
               "(no redistribution of prices). Derived z-sets are not prices (ADR-0201)."},
    "sample": {"grade": "synthetic", "terms": "Synthetic CI sample generated by credence_cal.sample; no vendor data."},
}
START = {"alpaca": "2016-01-01", "tiingo": "2000-01-01"}


def raw_dir(vendor: str) -> Path:
    return DATA / "raw" / vendor


def content_sha(df: pd.DataFrame) -> str:
    return sha256_hex(df.to_csv(index=False, lineterminator="\n").encode())


def load_raw(vendor: str, symbol: str) -> pd.DataFrame:
    if vendor == "sample":
        from .sample import sample_frame

        return sample_frame(symbol)
    return pd.read_parquet(raw_dir(vendor) / f"{symbol}.parquet")


def manifest_path(vendor: str) -> Path:
    return MANIFESTS / f"data-{vendor}.json"


def pull(vendor: str, end: str, symbols: list[str]) -> None:
    env = load_env()
    v = VENDORS[vendor](env)
    out = raw_dir(vendor)
    out.mkdir(parents=True, exist_ok=True)
    entries = {}
    for s in symbols:
        df = v.daily(s, START[vendor], end)
        df.to_parquet(out / f"{s}.parquet", index=False)
        entries[s] = {
            "rows": len(df),
            "first": df["date"].iloc[0] if len(df) else None,
            "last": df["date"].iloc[-1] if len(df) else None,
            "splits": int((df["split_ratio"] != 1.0).sum()),
            "dividends": int((df["dividend"] != 0.0).sum()),
            "contentSha256": content_sha(df),
            "fileSha256": sha256_hex((out / f"{s}.parquet").read_bytes()),
        }
        print(f"{s:6} {entries[s]['rows']:5} rows {entries[s]['first']} .. {entries[s]['last']}", flush=True)
    manifest = {
        "vendor": vendor,
        "licence": LICENCE[vendor],
        "pulledAt": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "window": {"start": START[vendor], "end": end},
        "listed": list(LISTED),
        "symbols": entries,
    }
    write_json(manifest_path(vendor), manifest)
    print(f"manifest -> {manifest_path(vendor)}")


def verify(vendor: str) -> dict:
    """Check every raw file against the committed manifest; return the manifest. Raises on mismatch."""
    import json

    m = json.loads(manifest_path(vendor).read_text())
    bad = []
    for s, e in m["symbols"].items():
        p = raw_dir(vendor) / f"{s}.parquet"
        if not p.exists():
            bad.append(f"{s}: missing {p}")
            continue
        got = content_sha(pd.read_parquet(p))
        if got != e["contentSha256"]:
            bad.append(f"{s}: content sha {got[:12]} != manifest {e['contentSha256'][:12]}")
    if bad:
        raise SystemExit("raw data does not match the pinned manifest:\n  " + "\n  ".join(bad))
    return m


CROSSCHECK_PATH = MANIFESTS / "crosscheck-alpaca-polygon.json"
CROSSCHECK_PER_ASSET = (4, 2)  # the largest |r| weekend/holiday gaps, plus seeded random ones


def crosscheck(end: str | None = None) -> dict:
    """Compare the pinned Alpaca bars with Polygon/Massive's official daily open/close (free tier: last
    2 years, 5 requests/minute) on the gaps that matter most: per listed asset the largest |r| WEEKEND /
    HOLIDAY_WEEKEND gaps of the last two years, plus seeded random ones. Each gap needs two calls (the
    previous close and the open). Only relative differences are written (no vendor prices are committed)."""
    import numpy as np

    from .vendors import Polygon

    m = verify("alpaca")
    end = end or m["window"]["end"]
    since = (dt.date.fromisoformat(end) - dt.timedelta(days=720)).isoformat()
    g = pd.read_parquet(DATA / "work" / "alpaca" / "gaps.parquet")
    poly = Polygon(load_env())
    rng = np.random.default_rng(20260928)
    rows = []
    for s in LISTED:
        gs = g[(g["symbol"] == s) & (g["type"] != 1) & (g["date"] >= since) & (g["date"] <= end)]
        worst = gs.reindex(gs["r"].abs().sort_values(ascending=False).index).head(CROSSCHECK_PER_ASSET[0])
        rest = gs.drop(worst.index)
        pick = pd.concat([worst, rest.iloc[sorted(rng.choice(len(rest), CROSSCHECK_PER_ASSET[1], replace=False))]])
        raw = load_raw("alpaca", s).set_index("date")
        for x in pick.itertuples(index=False):
            a_prev, a_open = float(raw.loc[x.prev, "close"]), float(raw.loc[x.date, "open"])
            p_prev, p_open = poly.open_close(s, x.prev), poly.open_close(s, x.date)
            if p_prev.get("status") != "OK" or p_open.get("status") != "OK":
                rows.append({"symbol": s, "date": x.date, "prev": x.prev, "status": f"{p_prev.get('status')}/{p_open.get('status')}"})
                continue
            r_poly = x.split * (float(p_open["open"]) + x.dividend) / float(p_prev["close"]) - 1.0
            rows.append({"symbol": s, "date": x.date, "prev": x.prev, "type": int(x.type), "status": "OK",
                         "prevCloseRelDiff": round(a_prev / float(p_prev["close"]) - 1.0, 8),
                         "openRelDiff": round(a_open / float(p_open["open"]) - 1.0, 8),
                         "gapDiffBps": round((float(x.r) - r_poly) * 1e4, 4)})
            print(f"{s:5} {x.date} gap diff {rows[-1]['gapDiffBps']:+.4f} bp", flush=True)
    ok = [r for r in rows if r["status"] == "OK"]
    doc = {"kind": "credence.crosscheck.v1", "primary": "alpaca (SIP daily bars)", "reference": "polygon /v1/open-close (official, unadjusted)",
           "window": {"start": since, "end": end}, "checked": len(rows), "matched": len(ok),
           "maxAbsGapDiffBps": max((abs(r["gapDiffBps"]) for r in ok), default=None),
           "maxAbsPriceRelDiff": max((max(abs(r["prevCloseRelDiff"]), abs(r["openRelDiff"])) for r in ok), default=None),
           "rows": rows}
    write_json(CROSSCHECK_PATH, doc)
    print(f"crosscheck: {len(ok)}/{len(rows)} matched; max |gap diff| {doc['maxAbsGapDiffBps']} bp -> {CROSSCHECK_PATH}")
    return doc


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(prog="credence_cal.data")
    ap.add_argument("cmd", choices=["pull", "verify", "crosscheck"])
    ap.add_argument("--vendor", default="alpaca", choices=list(VENDORS))
    ap.add_argument("--end", default=None, help="last date to pull (default: yesterday)")
    ap.add_argument("--symbols", default=None, help="comma-separated (default: listed + comparables)")
    a = ap.parse_args(argv)
    if a.cmd == "pull":
        end = a.end or (dt.date.today() - dt.timedelta(days=1)).isoformat()
        pull(a.vendor, end, a.symbols.split(",") if a.symbols else universe())
    elif a.cmd == "crosscheck":
        crosscheck(a.end)
    else:
        m = verify(a.vendor)
        print(f"{len(m['symbols'])} symbols match manifest-{a.vendor} (pulled {m['pulledAt']})")


if __name__ == "__main__":
    sys.exit(main())
